export const GET_LOCATION = "GET_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";

export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR";

export const GET_FORECAST_WEATHER = "GET_FORECAST_WEATHER";
export const FORECACT_WEATHER_ERROR = "FORECACT_WEATHER_ERROR";